// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/pingpong.proto

package pingpongpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_pingpong_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingpong_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_pingpong_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PongReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongReply) Reset() {
	*x = PongReply{}
	mi := &file_proto_pingpong_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongReply) ProtoMessage() {}

func (x *PongReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pingpong_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongReply.ProtoReflect.Descriptor instead.
func (*PongReply) Descriptor() ([]byte, []int) {
	return file_proto_pingpong_proto_rawDescGZIP(), []int{1}
}

func (x *PongReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_pingpong_proto protoreflect.FileDescriptor

const file_proto_pingpong_proto_rawDesc = "" +
	"\n" +
	"\x14proto/pingpong.proto\x12\bpingpong\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\tPongReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2@\n" +
	"\bPingPong\x124\n" +
	"\x04Ping\x12\x15.pingpong.PingRequest\x1a\x13.pingpong.PongReply\"\x00B0Z.github.com/riceriley59/synkra/proto;pingpongpbb\x06proto3"

var (
	file_proto_pingpong_proto_rawDescOnce sync.Once
	file_proto_pingpong_proto_rawDescData []byte
)

func file_proto_pingpong_proto_rawDescGZIP() []byte {
	file_proto_pingpong_proto_rawDescOnce.Do(func() {
		file_proto_pingpong_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pingpong_proto_rawDesc), len(file_proto_pingpong_proto_rawDesc)))
	})
	return file_proto_pingpong_proto_rawDescData
}

var file_proto_pingpong_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pingpong_proto_goTypes = []any{
	(*PingRequest)(nil), // 0: pingpong.PingRequest
	(*PongReply)(nil),   // 1: pingpong.PongReply
}
var file_proto_pingpong_proto_depIdxs = []int32{
	0, // 0: pingpong.PingPong.Ping:input_type -> pingpong.PingRequest
	1, // 1: pingpong.PingPong.Ping:output_type -> pingpong.PongReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pingpong_proto_init() }
func file_proto_pingpong_proto_init() {
	if File_proto_pingpong_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pingpong_proto_rawDesc), len(file_proto_pingpong_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pingpong_proto_goTypes,
		DependencyIndexes: file_proto_pingpong_proto_depIdxs,
		MessageInfos:      file_proto_pingpong_proto_msgTypes,
	}.Build()
	File_proto_pingpong_proto = out.File
	file_proto_pingpong_proto_goTypes = nil
	file_proto_pingpong_proto_depIdxs = nil
}
